### ISSUE TITLE
Got the following error when tried to run ear-pc.exe

### ISSUE THREAD

**Issue by ghost** [radiance-project/ear-pc#10]
Traceback (most recent call last):
  File "main.py", line 679, in <module>
  File "eel\__init__.py", line 163, in start
  File "eel\__init__.py", line 191, in show
  File "eel\browsers.py", line 63, in open
  File "eel\electron.py", line 11, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by ghost** [comment]
It as supposed to be launcher.exe
