### ISSUE TITLE
Error "Unhandled exception in script"

### ISSUE THREAD

**Issue by FERGAZA** [radiance-project/ear-pc#3]
I get this error when opening the ``launcher.exe``

![Error](https://github.com/radiance-project/ear-pc/assets/68644731/670111b8-9664-49da-aac5-979e8db8774c)

```
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 398, in _make_request
  File "urllib3\connection.py", line 239, in request
  File "http\client.py", line 1282, in request
  File "http\client.py", line 1328, in _send_request
  File "http\client.py", line 1277, in endheaders
  File "http\client.py", line 1037, in _send_output
  File "http\client.py", line 975, in send
  File "urllib3\connection.py", line 205, in connect
  File "urllib3\connection.py", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x0000023206349C30>, 'Connection to localhost timed out. (connect timeout=1)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=17079): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023206349C30>, 'Connection to localhost timed out. (connect timeout=1)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 686, in <module>
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 553, in send
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='localhost', port=17079): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000023206349C30>, 'Connection to localhost timed out. (connect timeout=1)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 688, in <module>
  File "main.py", line 681, in main
  File "eel\__init__.py", line 163, in start
  File "eel\__init__.py", line 191, in show
  File "eel\browsers.py", line 63, in open
  File "eel\electron.py", line 11, in run
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by mrbrickstar** [comment]
Hey, does this happen when you open the launcher or after it installed all the files?

**Comment by FERGAZA** [comment]
It happens right after opening the file, there's no more files in the folder besides a **devicesndpreferences.db** that is created once I open it

**Comment by mrbrickstar** [comment]
This error sounds more like you are trying to open ear-pc.exe without having downloaded everything. Please delete all files you have downloaded so far and try to install it again using this guide: 

1. Go to https://github.com/radiance-project/ear-pc/releases/
2. Find the newest release
3. Download ONLY launcher.exe. The other stuff is irrelevant
4. Launch launcher.exe
(If you have issues with windows defender or another antivirus, just ignore them for now. Some programms might falsly identify the launcher as a trojan, which it is not, as the launcher is open source. Just have a google for "false positiv antivirus" if you want more information)
5. The Launcher should now install all necessary dependencies

And you're done. You should now have a new Icon on your desktop and ear (PC) should be discoverable from your windows search.

In some cases a bug we are currently working on prevents the installer from creating these shortcuts tho. If you ran the launcher but are unable to locate the app on your pc, please try the following: 


1. Navigate to C:\Users\<your username>\AppData\Local\Programs\ear-pc
2. Right click ear-pc.exe
3. Select "Pin to start"


After that, you should have a little icon in your start window.

If this doesn't fix your issues, please continue this thread.

**Comment by FERGAZA** [comment]
Yes that was the issue, as a complete idiot I downloaded the **ear-pc.exe** instead and I don't know why I was so sure it was the correct and only executable. Thanks for making such a visually pleasing and convenient app and sorry for the inconvenience.
